import type { Metadata } from 'next'
import { Oxanium } from 'next/font/google'
import './globals.scss'
import Header from './general/header/Header'
import { CSSProperties } from 'react'
import Footer from './general/footer/Footer'

const oxanium = Oxanium({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mari 3D',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oxanium.className} style={{'--fontMain':oxanium.style} as CSSProperties}>
				<Header/>
				{children}
				<Footer/>
			</body>
    </html>
  )
}
